Get the locations of New York stations

In [10]:
import pandas as pd

def get_station_locations():
    df = pd.read_csv("http://web.mta.info/developers/data/nyct/subway/StationEntrances.csv")
    return df

In [11]:
print get_station_locations()

     Division              Line                   Station_Name  \
0         BMT           Astoria                   Ditmars Blvd
1         BMT           Astoria                   Ditmars Blvd
2         BMT           Astoria                   Ditmars Blvd
3         BMT           Astoria                   Ditmars Blvd
4         BMT           Astoria           Astoria Blvd-Hoyt Av
5         BMT           Astoria           Astoria Blvd-Hoyt Av
6         BMT           Astoria           Astoria Blvd-Hoyt Av
7         BMT           Astoria           Astoria Blvd-Hoyt Av
8         BMT           Astoria                 30 Av-Grand Av
9         BMT           Astoria                 30 Av-Grand Av
10        BMT           Astoria                 30 Av-Grand Av
11        BMT           Astoria                 30 Av-Grand Av
12        BMT           Astoria                       Broadway
13        BMT           Astoria                       Broadway
14        BMT           Astoria                       Broadway
15        BMT           Astoria            36 Av-Washington Av
16        BMT           Astoria            36 Av-Washington Av
17        BMT           Astoria            36 Av-Washington Av
18        BMT           Astoria                 39 Av-Beebe Av
19        BMT           Astoria                 39 Av-Beebe Av
20        BMT          Broadway                         5th Av
21        BMT          Broadway                         5th Av
22        BMT          Broadway                         5th Av
23        BMT          Broadway                         5th Av
24        BMT          Broadway                        57th St
25        BMT          Broadway                        57th St
26        BMT          Broadway                        57th St
27        BMT          Broadway                        57th St
28        BMT          Broadway                        49th St
29        BMT          Broadway                        49th St
...       ...               ...                            ...
1836      IRT            Jerome        Yankee Stadium-161st St
1837      IRT            Jerome        Yankee Stadium-161st St
1838      IRT            Jerome        Yankee Stadium-161st St
1839      IRT            Jerome        Yankee Stadium-161st St
1840      IND          6 Avenue          Broadway-Lafayette St
1841      IND          6 Avenue          Broadway-Lafayette St
1842      IND            Culver                           Av I
1843      IND            Culver                           Av U
1844      IND  Queens Boulevard           63rd Drive-Rego Park
1845      IND  Queens Boulevard           63rd Drive-Rego Park
1846      IND  Queens Boulevard           63rd Drive-Rego Park
1847      IND  Queens Boulevard           63rd Drive-Rego Park
1848      IND  Queens Boulevard  Jackson Heights-Roosevelt Ave
1849      IND  Queens Boulevard  Jackson Heights-Roosevelt Ave
1850      IND  Queens Boulevard  Jackson Heights-Roosevelt Ave
1851      IND         Crosstown  Long Island City-Court Square
1852      IND         Crosstown  Long Island City-Court Square
1853      IRT  Broadway-7th Ave                       207th St
1854      IRT  Broadway-7th Ave                        96th St
1855      IRT  Broadway-7th Ave                        72nd St
1856      IRT  Broadway-7th Ave        59th St-Columbus Circle
1857      IRT  Broadway-7th Ave        59th St-Columbus Circle
1858      IRT   Eastern Parkway                        Hoyt St
1859      IRT         Lexington                        59th St
1860      IRT         Lexington                       Canal St
1861      IRT         Lexington                       Canal St
1862      IRT         Lexington                       Canal St
1863      IRT         Lexington                      Fulton St
1864      IRT         Lexington                      Fulton St
1865      IRT         Lexington                      Fulton St

      Station_Latitude  Station_Longitude Route_1 Route_2 Route_3 Route_4  \
0            40.775036         -73.912034       N       Q     NaN     NaN
1            40.775036         -73.912034       N       Q     NaN     NaN
2            40.775036         -73.912034       N       Q     NaN     NaN
3            40.775036         -73.912034       N       Q     NaN     NaN
4            40.770258         -73.917843       N       Q     NaN     NaN
5            40.770258         -73.917843       N       Q     NaN     NaN
6            40.770258         -73.917843       N       Q     NaN     NaN
7            40.770258         -73.917843       N       Q     NaN     NaN
8            40.766779         -73.921479       N       Q     NaN     NaN
9            40.766779         -73.921479       N       Q     NaN     NaN
10           40.766779         -73.921479       N       Q     NaN     NaN
11           40.766779         -73.921479       N       Q     NaN     NaN
12           40.761820         -73.925508       N       Q     NaN     NaN
13           40.761820         -73.925508       N       Q     NaN     NaN
14           40.761820         -73.925508       N       Q     NaN     NaN
15           40.756804         -73.929575       N       Q     NaN     NaN
16           40.756804         -73.929575       N       Q     NaN     NaN
17           40.756804         -73.929575       N       Q     NaN     NaN
18           40.752882         -73.932755       N       Q     NaN     NaN
19           40.752882         -73.932755       N       Q     NaN     NaN
20           40.764811         -73.973347       N       Q       R     NaN
21           40.764811         -73.973347       N       Q       R     NaN
22           40.764811         -73.973347       N       Q       R     NaN
23           40.764811         -73.973347       N       Q       R     NaN
24           40.764664         -73.980658       N       Q       R     NaN
25           40.764664         -73.980658       N       Q       R     NaN
26           40.764664         -73.980658       N       Q       R     NaN
27           40.764664         -73.980658       N       Q       R     NaN
28           40.759901         -73.984139       N       Q       R     NaN
29           40.759901         -73.984139       N       Q       R     NaN
...                ...                ...     ...     ...     ...     ...
1836         40.827994         -73.925831      B        D       4     NaN
1837         40.827994         -73.925831      B        D       4     NaN
1838         40.827994         -73.925831      B        D       4     NaN
1839         40.827994         -73.925831      B        D       4     NaN
1840         40.725297         -73.996204       B       D       F       M
1841         40.725297         -73.996204       B       D       F       M
1842         40.625322         -73.976127       F     NaN     NaN     NaN
1843         40.596063         -73.973357       F     NaN     NaN     NaN
1844         40.729846         -73.861604       M       R     NaN     NaN
1845         40.729846         -73.861604       M       R     NaN     NaN
1846         40.729846         -73.861604       M       R     NaN     NaN
1847         40.729846         -73.861604       M       R     NaN     NaN
1848         40.746644         -73.891338       E       F       M       R
1849         40.746644         -73.891338       E       F       M       R
1850         40.746644         -73.891338       E       F       M       R
1851         40.746554         -73.943832       G     NaN     NaN     NaN
1852         40.746554         -73.943832       G     NaN     NaN     NaN
1853         40.864614         -73.918819       1     NaN     NaN     NaN
1854         40.793919         -73.972323       1       2       3     NaN
1855         40.778453         -73.981970       1       2       3     NaN
1856         40.768247         -73.981929       A       B       C       D
1857         40.768247         -73.981929       A       B       C       D
1858         40.690545         -73.985065       2       3     NaN     NaN
1859         40.762526         -73.967967       N       Q       R       4
1860         40.718803         -74.000193       J       N       Q       R
1861         40.718803         -74.000193       J       N       Q       R
1862         40.718803         -74.000193       J       N       Q       R
1863         40.710368         -74.009509       A       C       J       Z
1864         40.710368         -74.009509       A       C       J       Z
1865         40.710368         -74.009509       A       C       J       Z

     Route_5    ...     Staffing        Staff_Hours    ADA          ADA_Notes  \
0        NaN    ...         FULL                NaN  False                NaN
1        NaN    ...         FULL                NaN  False                NaN
2        NaN    ...         FULL                NaN  False                NaN
3        NaN    ...         FULL                NaN  False                NaN
4        NaN    ...         FULL                NaN  False                NaN
5        NaN    ...         FULL                NaN  False                NaN
6        NaN    ...         FULL                NaN  False                NaN
7        NaN    ...         FULL                NaN  False                NaN
8        NaN    ...         FULL                NaN  False                NaN
9        NaN    ...         FULL                NaN  False                NaN
10       NaN    ...         FULL                NaN  False                NaN
11       NaN    ...         FULL                NaN  False                NaN
12       NaN    ...         FULL                NaN  False                NaN
13       NaN    ...         FULL                NaN  False                NaN
14       NaN    ...         FULL                NaN  False                NaN
15       NaN    ...         FULL                NaN  False                NaN
16       NaN    ...         FULL                NaN  False                NaN
17       NaN    ...         FULL                NaN  False                NaN
18       NaN    ...         FULL                NaN  False                NaN
19       NaN    ...         FULL                NaN  False                NaN
20       NaN    ...         FULL                NaN  False                NaN
21       NaN    ...         FULL                NaN  False                NaN
22       NaN    ...         FULL                NaN  False                NaN
23       NaN    ...         FULL                NaN  False                NaN
24       NaN    ...         FULL                NaN  False                NaN
25       NaN    ...         FULL                NaN  False                NaN
26       NaN    ...         FULL                NaN  False                NaN
27       NaN    ...         FULL                NaN  False                NaN
28       NaN    ...         FULL                NaN   True    Northbound Only
29       NaN    ...         FULL                NaN   True    Northbound Only
...      ...    ...          ...                ...    ...                ...
1836     NaN    ...       Spc Ev  Used on Game Days   True                NaN
1837     NaN    ...       Spc Ev  Used on Game Days   True                NaN
1838     NaN    ...       Spc Ev  Used on Game Days   True                NaN
1839     NaN    ...       Spc Ev  Used on Game Days   True                NaN
1840       6    ...         NONE                NaN  False                NaN
1841       6    ...         NONE                NaN  False                NaN
1842     NaN    ...         NONE                NaN  False                NaN
1843     NaN    ...         NONE                NaN  False                NaN
1844     NaN    ...         NONE                NaN  False                NaN
1845     NaN    ...         NONE                NaN  False                NaN
1846     NaN    ...         NONE                NaN  False                NaN
1847     NaN    ...         NONE                NaN  False                NaN
1848       7    ...         NONE                NaN   True                NaN
1849       7    ...         NONE                NaN   True                NaN
1850       7    ...         NONE                NaN   True                NaN
1851     NaN    ...         NONE                NaN  False                NaN
1852     NaN    ...         NONE                NaN  False                NaN
1853     NaN    ...         NONE                NaN  False                NaN
1854     NaN    ...         NONE                NaN   True                NaN
1855     NaN    ...         NONE                NaN   True                NaN
1856       1    ...         NONE                NaN   True                NaN
1857       1    ...         NONE                NaN   True                NaN
1858     NaN    ...         NONE                NaN  False                NaN
1859       5    ...         NONE                NaN  False                NaN
1860       Z    ...         NONE                NaN   True  Bway Nass not ADA
1861       Z    ...         NONE                NaN   True  Bway Nass not ADA
1862       Z    ...         NONE                NaN   True  Bway Nass not ADA
1863       2    ...         NONE                NaN  False                NaN
1864       2    ...         NONE                NaN  False                NaN
1865       2    ...         NONE                NaN  False                NaN

      Free_Crossover  North_South_Street   East_West_Street Corner   Latitude  \
0               True             31st St           23rd Ave     NW  40.775149
1               True             31st St           23rd Ave     NE  40.774810
2               True             31st St           23rd Ave     NE  40.775025
3               True             31st St           23rd Ave     NW  40.774938
4               True             31st St     Hoyt Ave South     SW  40.770313
5               True             31st St     Hoyt Ave South     SE  40.770170
6               True             31st St     Hoyt Ave North     NW  40.771009
7               True             31st St     Hoyt Ave North     NE  40.770870
8               True             31st St           30th Ave     SW  40.766787
9               True             31st St           30th Ave     SE  40.766700
10              True             31st St           30th Ave     NW  40.767052
11              True             31st St           30th Ave     NE  40.766963
12              True             31st St           Broadway     SW  40.761880
13              True             31st St           Broadway     SE  40.761773
14              True             31st St           Broadway     NW  40.762217
15              True             31st St           36th Ave     SW  40.756478
16              True             31st St           36th Ave     SE  40.756379
17              True             31st St           36th Ave     NW  40.756796
18              True             31st St           39th Ave     NW  40.752901
19              True             31st St           39th Ave     SE  40.752491
20              True             5th Ave            60th St     NW  40.765156
21              True             5th Ave            60th St     SE  40.764728
22              True             5th Ave            60th St     NE  40.764849
23              True             5th Ave            60th St     SE  40.764657
24              True             7th Ave            57th St     SW  40.765365
25              True             7th Ave            57th St     SE  40.765298
26              True             7th Ave            57th St     NW  40.765796
27              True             7th Ave            57th St     NE  40.765639
28             False             7th Ave            49th St     SW  40.760486
29             False             7th Ave            49th St     NW  40.760621
...              ...                 ...                ...    ...        ...
1836            True           River Ave           161st St     SW  40.827605
1837            True           River Ave           161st St     SW  40.827529
1838            True           River Ave           161st St     SW  40.827461
1839            True           River Ave           161st St     SW  40.827399
1840            True        Lafayette St         Houston St     SW  40.724987
1841            True           Crosby St         Houston St     SE  40.725011
1842            True        McDonald Ave           Avenue J     NE  40.624301
1843            True        McDonald Ave  Gravesend Neck Rd     SE  40.595027
1844            True             63rd Dr        Queens Blvd     NW  40.730037
1845            True             63rd Dr        Queens Blvd     SW  40.729574
1846            True             64th Rd        Queens Blvd     SE  40.728847
1847            True             64th Rd        Queens Blvd     NW  40.729774
1848            True             75th St           Broadway     SE  40.745988
1849            True             75th St           Broadway     NE  40.746391
1850            True             74th St       Roosevelt Av     SW  40.746527
1851            True         Jackson Ave           45th Ave     NW  40.746869
1852            True        Court Square        Jackson Ave     SW  40.746243
1853           False            10th Ave           207th St     NE  40.864599
1854            True            Broadway            95th St      N  40.794611
1855            True            Broadway            72nd St     SE  40.778437
1856            True     Columbus Circle            59th St     SE  40.767654
1857            True     Columbus Circle            59th St     SE  40.767642
1858           False         Duffield St          Fulton St     NE  40.690433
1859            True       Lexington Ave            60th St     NW  40.762986
1860            True        Lafayette St           Canal St     NW  40.718589
1861            True        Lafayette St           Canal St     SW  40.718506
1862            True        Lafayette St           Canal St     NW  40.718638
1863            True            Broadway          Fulton St     SW  40.710944
1864            True            Broadway          Fulton St     NW  40.711026
1865            True            Broadway          Fulton St     NW  40.711112

      Longitude
0    -73.912074
1    -73.912151
2    -73.911891
3    -73.912337
4    -73.917978
5    -73.917755
6    -73.917167
7    -73.916935
8    -73.921629
9    -73.921406
10   -73.921409
11   -73.921192
12   -73.925638
13   -73.925399
14   -73.925349
15   -73.929993
16   -73.929766
17   -73.929740
18   -73.932903
19   -73.932936
20   -73.972501
21   -73.972396
22   -73.972306
23   -73.972229
24   -73.980341
25   -73.980033
26   -73.980012
27   -73.979764
28   -73.983974
29   -73.983904
...         ...
1836 -73.926282
1837 -73.926322
1838 -73.926362
1839 -73.926394
1840 -73.995628
1841 -73.995745
1842 -73.975817
1843 -73.973382
1844 -73.861343
1845 -73.861751
1846 -73.859668
1847 -73.860489
1848 -73.890208
1849 -73.890285
1850 -73.891461
1851 -73.943522
1852 -73.944011
1853 -73.918681
1854 -73.972053
1855 -73.981947
1856 -73.981423
1857 -73.981235
1858 -73.984323
1859 -73.967850
1860 -74.000552
1861 -74.000826
1862 -74.000623
1863 -74.009403
1864 -74.009190
1865 -74.009382

[1866 rows x 30 columns]